# Generated by Django 6.0.1 on 2026-03-02 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên danh mục')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên chi nhánh')),
                ('address', models.CharField(max_length=500, verbose_name='Địa chỉ')),
                ('latitude', models.FloatField(verbose_name='Vĩ độ (Lat)')),
                ('longitude', models.FloatField(verbose_name='Kinh độ (Lon)')),
                ('store_type', models.CharField(choices=[('MAIN', 'Trụ sở chính'), ('SUB', 'Chi nhánh nhỏ')], default='SUB', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Tên khách')),
                ('phone', models.CharField(max_length=20, verbose_name='SĐT')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền')),
                ('status', models.CharField(default='Pending', max_length=50, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá bán (VNĐ)')),
                ('original_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Giá gốc (VNĐ)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ảnh')),
                ('is_flash_sale', models.BooleanField(default=False, verbose_name='Hàng Flash Sale')),
                ('stock', models.IntegerField(default=0, verbose_name='Tồn kho')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Danh mục')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
