# Generated by Django 6.0.1 on 2026-03-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebranch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='branches/', verbose_name='Ảnh chi nhánh'),
        ),
    ]
