# Generated by Django 6.0.1 on 2026-04-01 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_stocktransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Admin Tổng (Toàn quyền)'), ('BRANCHADMIN', 'Admin Chi Nhánh'), ('STAFF', 'Nhân viên cửa hàng'), ('CUSTOMER', 'Khách hàng')], default='CUSTOMER', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.storebranch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
